# site settings
title: Smart Light Apps
subtitle:
email: smartlightsapps@gmail.com
description: A home to all smart lights
baseurl: ""# the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Delhi
state: New Delhi
zip_code: 110044
country: India
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 60

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
